version: "3"

services:
  postgres:
    container_name: PostgreSQL
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./tmp/data/db:/var/lib/postgresql/data

  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: Node-server

volumes:
  mongo_db: {}
